### ISSUE TITLE
Can't figure out how to send the entire tree to the flipper...

### ISSUE THREAD

**Issue by PinkFreud** [Gioman101/FlipperAmiibo#1]
Try as I might, I simply cannot figure out how to send the entire uncompressed tree of files to my flipper.

qflipper only lets me upload individual files - selecting a directory and hitting Open merely causes the file browser to enter the directory, rather than select it for uploading.  I can mount the sd card on my pc and copy the tree to the nfc directory on the card, but when I remount the card in the flipper and browse saved cards, nothing in this tree shows up.

What am I missing here?  Do all of these dumps have to be in nfc/ itself, without subdirectories?  Is there something I'm just not doing right?

**Comment by PinkFreud** [comment]
Never mind.  It's late - I missed that the down arrow launches an actual file browser, and not a separate app.  Disregard - I can browse this now!

**Comment by Gioman101** [comment]
Awesome glad you figured it out & sorry I was asleep when you made this I just dropped all the files onto SD instead of using the software of qflipper & use file browser to access on flipper.

**Comment by PinkFreud** [comment]
No worries - I probably should have been asleep for missing the browser on the Flipper!  Thanks again.  :)

Incidentally, this app seems to generate the UID wrong - a good read of an Amiibo card here gives me:

UID: 04 48 84 82 46 76 80
...
Page 0: 04 48 84 40
Page 1: 82 46 76 80

The 7 byte UID is the first 3 bytes of page 0, followed by all 4 from page 1.  The incorrect UID doesn't seem to affect Amiibo reads for the moment, but it's possible Nintendo could change that to discourage people from using copied Amiibos in the future.

Anyway, thanks again!
