### ISSUE TITLE
"This is not an amiibo" error, Monster Hunter Rise Sunbreak

### ISSUE THREAD

**Issue by GeoGenesis** [Gioman101/FlipperAmiibo#12]
MH Rise Amiibos don't seem to be working.
Getting 2115 errors when attempting to read through game and "This is not an amiibo" error when checking through Switch amiibo check.

Flipper Zero Firmware: ECE142A6
MH RIse Version: 10.0.2
Switch Version: 14.1.2

Was able to successfully scan following these steps:

Reset Magnamalo Amiibo via switch settings: 
system > amiibo > reset amiibo > scan into MH

But outside of that, have been exclusively getting errors.

**Comment by RogueMaster** [comment]
This is possible due to an issue with the converter PY script and PWD/PACK on the last pages. I opened an issue there...

**Comment by GeoGenesis** [comment]
Latest update #14 still getting the same error both in-game and in amiibo system menu.

Magnamalo appears to remain functional, however, all other MH amiibos are not registering as amiibos to the system.

Attempted troubleshooting:

- Updating Flipper Firmware to latest Dev build
- Adding additional NFC assets from [UberGuidoZ](https://github.com/UberGuidoZ)

Errors persisting. Screenshot below. 
https://pbs.twimg.com/media/FXdUo66VQAAjTLa?format=jpg&name=large

**Comment by GeoGenesis** [comment]
Update commit from @RogueMaster has enabled amiibo functionality fully for all amiibo files in the MH_Rise folder.

Happy hunting, folks!
