### ISSUE TITLE
"Selected file is too large" when uploading Animal_Crossing using QFlipper

### ISSUE THREAD

**Issue by arazumny** [Gioman101/FlipperAmiibo#18]
Steps to reproduce:

1. Download Animal_Crossing
2. Attempt to upload to Flipper using QFlipper

Error;
![image](https://user-images.githubusercontent.com/109411422/184616617-a052fbcc-394b-4ae9-a865-ac843867da36.png)

**Comment by arazumny** [comment]
Additional information: This issue only occurs when attempting to upload this specific folder, or when uploading the total FlipperAmiibo folder. The issue does not occur when uploading other Amiibo folders.

**Comment by arazumny** [comment]
Additional information: When I upload the sub-folders individually, I encounter no issues.

**Comment by arazumny** [comment]
Additional information: When I upload the sub-folders individually, I encounter no issues.

**Comment by Gioman101** [comment]
I would recommend using a SD card reader instead to drop the entire repository instead of Qflipper
