### ISSUE TITLE
Legend of Zelda Amiibo do not seem to work on Zelda BOTW

### ISSUE THREAD

**Issue by Xiarno** [Gioman101/FlipperAmiibo#33]
I was trying to use the Zelda amiibo on Zelda BOTW on the Switch but it doesn't seem to detect them at all.

**Comment by testAccountBecauseBored** [comment]
Maybe try going to breath of the wild settings (on the same screen as save/load), and selecting “use Amiibo,” and then in the in-game runes, select the Amiibo icon and then scan your Amiibo/Flipper

**Comment by Xiarno** [comment]
> Maybe try going to breath of the wild settings (on the same screen as save/load), and selecting “use Amiibo,” and then in the in-game runes, select the Amiibo icon and then scan your Amiibo/Flipper

Yes, I know how to use Amiibo in game. But it still doesn't detect them.

**Comment by testAccountBecauseBored** [comment]
Idk I don’t own a flipper I’m just planning on making an amiibo emulator

**Comment by RunningDroid** [comment]
What firmware/firmware version do you have on your Flipper?
Are you able to get other (physical) Amiibos/amiibo clones to work?

I'm unable to reproduce this bug, but I'm running the [Unleashed firmware](https://github.com/DarkFlippers/unleashed-firmware), not the Official firmware.

**Comment by pickerin** [comment]
Same issue.  However, having the Flipper read a real Amiibo and then try to emulate gives the same behavior (nothing).  Using that same Amiibo works as expected.

Something is off on the emulation from the Flipper, not the source files.

**Comment by kbembedded** [comment]
If you go in to system settings, amiibo, reset amiibo, and then emulate the tag, does it get picked up?

Additionally, if you have a silicone case on the Flipper, try removing it to get it that much closer to the reader.

**Comment by Exxion** [comment]
Indeed works for me with stock firmware and with (at least one of) the files from this repo. The positioning is a bit fiddly, but it did eventually work.

**Comment by pickerin** [comment]
Got it working, with the case, on stock firmware, by rotating the Flipper Zero so that it was perpendicular to the Switch, with the D-pad ABOVE the screen (so you're holding it sideways).  Then the "sweet spot" to get it to read is right under the center button of the d-pad.  Works reliably in that orientation, but WILL NOT read if I'm holding it so I can read the screen.

**Comment by RunningDroid** [comment]
> by rotating the Flipper Zero so that it was perpendicular to the Switch with the D-pad ABOVE the screen (so you're holding it sideways).

This sounds like your Flipper isn't transmitting as strong a signal as it should be or something. Mine works (with the case) when I hold it parallel to my switch over/on the right joystick.

**Comment by pickerin** [comment]
> This sounds like your Flipper isn't transmitting as strong a signal as it should be or something. Mine works (with the case) when I hold it parallel to my switch over/on the right joystick.

Dunno.  I see a lot of folks having issues with their Switch.  I just got it, so I haven't played with emulation a lot yet, I'll be curious to see if I have transmission issues with other devices.  Might be my OLED switch, might be the Flipper, hard to say with one use case.

**Comment by RunningDroid** [comment]
> Might be my OLED switch

I hadn't considered that differences between the Switch models might play a role, I've been testing with a non-OLED Switch (original or first gen or whatever.)

**Comment by pickerin** [comment]
> I've been testing with a non-OLED Switch (original or first gen or whatever.)

If it's a hackable serial number, worth some money towards an upgrade for testing.  :)

**Comment by Nesquik-RGB** [comment]
I had the same problem with my new TOTK OLED, swapped out the joy-cons to my old neon ones and it works fine. Seems the newer joycons have something in them to block emulated signals, no luck with flipper or phone emulation but real Amiibos work fine on them.

**Comment by pickerin** [comment]
> I had the same problem with my new TOTK OLED, swapped out the joy-cons to my old neon ones and it works fine. Seems the newer joycons have something in them to block emulated signals, no luck with flipper or phone emulation but real Amiibos work fine on them.

Pretty sure it's an orientation problem on the OLEDs.  It's almost like the newer joycons are "polarized" for the NFC.
I'm able to reliably get the Flipper to emulate Amiibos by holding it vertically (dpad above screen) and then tapping the joycon reader (thumstick) just below the center button on the dpad.  Agree the older joycons work better; but they didn't do anything to block emulation (they can't).

**Comment by RunningDroid** [comment]
> > I've been testing with a non-OLED Switch (original or first gen or whatever.)
> 
> If it's a hackable serial number, worth some money towards an upgrade for testing. :)

It is hackable, but I've been procrastinating upgrading and justifying it as giving myself something to do if/when Nintendo shuts off the Switch servers.

I tried looking into the differences between the OLED Switch's joycons and the older joycons, but I'm not finding much info on the web.  GBAtemp has a thread asking about [switch hardware revisions](https://gbatemp.net/threads/how-many-hardware-revisions-does-the-switch-have.512591/) where some people [mention](https://gbatemp.net/threads/how-many-hardware-revisions-does-the-switch-have.512591/post-8170556) [some](https://gbatemp.net/threads/how-many-hardware-revisions-does-the-switch-have.512591/post-8469298) of the joycon model numbers/revisions (I have HAC-A-JC*-C2, with the * being R for the right, and L for the left.) And I found iFixit's [Switch](https://www.ifixit.com/Teardown/Nintendo+Switch+Teardown/78263) and [OLED Switch](https://www.ifixit.com/News/53272/nintendo-switch-oled-teardown-more-than-screen-deep) teardowns, but the teardown for the OLED Switch doesn't give us a look at the NFC antenna in the right joycon. We do get X-ray images of [both](https://guide-images.cdn.ifixit.com/igi/BcP6qAlRJZ2ZHWRt.huge) [devices](https://valkyrie.cdn.ifixit.com/media/2021/10/13092322/Switch_OLED_Xray-2048x1104.jpg) (including joycons), however the only thing they appear to indicate is that both devices have the antenna turned 90 degrees (facing the joycon's rail.)

**Comment by Nesquik-RGB** [comment]
> I'm able to reliably get the Flipper to emulate Amiibos by holding it vertically (dpad above screen) and then tapping the joycon reader (thumstick) just below the center button on the dpad. 

Good to know they still work, I will have to give it another try with this method. Thanks for the tip!

**Comment by pickerin** [comment]
> I tried looking into the differences between the OLED Switch's joycons and the older joycons, but I'm not finding much info on the web. GBAtemp has a thread asking about [switch hardware revisions](https://gbatemp.net/threads/how-many-hardware-revisions-does-the-switch-have.512591/) where some people [mention](https://gbatemp.net/threads/how-many-hardware-revisions-does-the-switch-have.512591/post-8170556) [some](https://gbatemp.net/threads/how-many-hardware-revisions-does-the-switch-have.512591/post-8469298) of the joycon model numbers/revisions (I have HAC-A-JC*-C2, with the * being R for the right, and L for the left.) And I found iFixit's [Switch](https://www.ifixit.com/Teardown/Nintendo+Switch+Teardown/78263) and [OLED Switch](https://www.ifixit.com/News/53272/nintendo-switch-oled-teardown-more-than-screen-deep) teardowns, but the teardown for the OLED Switch doesn't give us a look at the NFC antenna in the right joycon. We do get X-ray images of [both](https://guide-images.cdn.ifixit.com/igi/BcP6qAlRJZ2ZHWRt.huge) [devices](https://valkyrie.cdn.ifixit.com/media/2021/10/13092322/Switch_OLED_Xray-2048x1104.jpg) (including joycons), however the only thing they appear to indicate is that both devices have the antenna turned 90 degrees (facing the joycon's rail.)

Thanks for looking into it, it definitely works well if you change the orientation of the Flipper and doesn't work at all when horizontal.  Swapping the JoyCons to "older" ones allows the Flipper to work horizontal on the same Switch.

It's all good, it works reliably by rotating the Flipper.

**Comment by Gioman101** [comment]
Thanks for all the great tips on how to position the flipper to be detected by the joycon also my best outcome for amiibos is using a switch controller for my flipper works all the time very solid compared to using the joycon as they produce less of an nfc signal so it's why you gotta be so close to have it read the correct way
