### ISSUE TITLE
Depreciated file for TOTK amiibo

### ISSUE THREAD

**Issue by ZerkerEOD** [Gioman101/FlipperAmiibo#39]
Hello, I am getting that the TOTK link amiibo is depreciated. Do you know how to fix this?

**Comment by ZerkerEOD** [comment]
Nevermind I updated my flipper and it's working now.

**Comment by systemofadl** [comment]
I am also getting this error, I have updated the flipper, deleted the file and reuploaded, I tried renaming it.
Any advice?
