### ISSUE TITLE
This is a question

### ISSUE THREAD

**Issue by ZekePolarisBSH** [Gioman101/FlipperAmiibo#42]
Do you need Kazuya and Sephiroth and Pyra and Mythra amiibos?

**Comment by Gioman101** [comment]
I would gladly take them & if they are not converted to flipper format I'll do that then with the amiibos files

**Comment by ZekePolarisBSH** [comment]
They should be ready for Flipper use I have used even though Pyra and Mythra isn't even out yet according to Google. Also I just realized that I never uploaded to GitHub before and I can't find the original content that I got them from. But iirc, it is basically the same set from UberGuidoz but updated? Hopefuly GitHub lets me upload it like how every other site works. I maybe a programmer of BSH but I am still a N00b.

**Comment by ZekePolarisBSH** [comment]
I think I did it!!! My first upload!!! I have shared the amiibos I have, I even reset them so they are not linked to accounts.

**Comment by ZekePolarisBSH** [comment]
I used my Flipper to verify I am account owner LOL

**Comment by marcuslyons** [comment]
@ZekePolarisBSH: Looks like you've uploaded them to your fork, but you'll need to [open a Pull Request ](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)to get them added into this repo

**Comment by ZekePolarisBSH** [comment]
Once I figure out how to do that I will

**Comment by marcuslyons** [comment]
If you follow the steps in [this link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) you'll be able to do that through the browser pretty easily, and then you'll have your first PR and contribution

**Comment by crc8109** [comment]
> Once I figure out how to do that I will

If you need a hand, lmk! I can help out in about an hr if you want to hop in a Hangouts room and I can help you learn the workflow. Patiently waiting on this update :sweat_smile:

**Comment by ZekePolarisBSH** [comment]
I think I did it, please tell me I did it right

**Comment by ZekePolarisBSH** [comment]
If I find Sora, some how, I send him to you
