### ISSUE TITLE
Pikmin tag "This is not an amiibo." error

### ISSUE THREAD

**Issue by CheeseSodaPunch** [Gioman101/FlipperAmiibo#45]
When I try to register Owner and Nickname for the Pikmin tag, I consistently receive the "This is not an amiibo." error message. I'm not experiencing this elsewhere with other amiibo tags that I have tried so far.

**Comment by Excelling-At-Excel** [comment]
Use the Pikmin in the "Other" folder.  That one worked for me (For what I needed it for)

**Comment by CheeseSodaPunch** [comment]
Sorry I didn't respond sooner. Your solution checks out. It just seems to be the NFC in the Pikmin_Amiibo folder that does not work. Not sure if the repo owner wants to remove that.

**Comment by ZekePolarisBSH** [comment]
I had this happen to me before on one of my amiibos. It started happening since that one update and Idk how too make it stop. But far as I can see, it seems to work once I back out and try again. Are you using CFW? Don't think it is only for the Pikmin amiibo.

**Comment by CheeseSodaPunch** [comment]
I believe I've run into this issue on both the latest stock firmware and some CFW.

**Comment by ZekePolarisBSH** [comment]
For me it is only happening with Kazuya amiibo. Maybe just lucky. But yea
ever since that update I noticed this issue. Glad they don't ban us for
using them though
