### ISSUE TITLE
Should we move the game folders to the root of the repo?

### ISSUE THREAD

**Issue by derekpovah** [Gioman101/FlipperAmiibo#5]
I use git to manage my Flipper SD card so it would be super cool if I could add this as a submodule. 

Right now, the directory structure would have to look like this:
```
nfc
├── Amiibo
│   └── Amiibo Database 2018 - 2022
│       ├── 01- Super Smash Bros
│       ├── 02- Super Mario
│       ├── ...
```

But I'd want it to look like this:
```
nfc
├── Amiibo
│   ├── 01- Super Smash Bros
│   ├── 02- Super Mario
│   ├── ...
```

**Comment by JulyIghor** [comment]
Also numbers makes no sense. Flipper does not sort files and they are displayed in the order of files copied to FAT32.
