### ISSUE TITLE
Amiibo not working on 3DS

### ISSUE THREAD

**Issue by Crispymug** [Gioman101/FlipperAmiibo#56]
I own a new Nintendo 3DS XL and the amiibos don’t appear to work. All my games come from the H shop. I don’t know whether this is an issue with the H shop games or with using the flipper with the 3DS. Is anyone able to help?

**Comment by Gioman101** [comment]
This is ment for nintendo switch not the 3DS

**Comment by Crispymug** [comment]
Surely it would be cross compatible. Do they not use the same technology?

**Comment by sundhaug92** [comment]
They use the same tech, you may want to check that the amiibo you're using are compatible with the game, and where the respective antenna of the 3DS and Flipper are

**Comment by RossiGiova** [comment]
I have tried it now on my New Nintendo 3ds xl and it works well, is it possible that the "classic" 3ds xl needs an adapter for the nfc tecnology?

**Comment by Crispymug** [comment]
I have a new Nintendo 3DS XL so I’ll have to check compatibility with the titles I’m using. I’ll retry tonight and see whether certain titles don’t work with the flipper.

**Comment by Crispymug** [comment]
Issue solved
Part of setting up homebrew installed a module that took control of amiibo data without warning and after disabing the module it works fine.
