### ISSUE TITLE
Issues with "pikmin" and "Qbby"

### ISSUE THREAD

**Issue by ZombieHunter512** [Gioman101/FlipperAmiibo#7]
When using Pikmin Amiibo, either in the "other" folder or the "pikmin" folder with my flipper on my switch it will say "this is not an Amiibo". It will also do this for the same files with "Qbby", any other Amiibo's work just fine.

**Comment by RogueMaster** [comment]
This is possible due to an issue with the converter PY script and PWD/PACK on the last pages. I opened an issue there...

**Comment by ajosephau** [comment]
If you're looking to emulate the "Pikmin" character for Mario Kart 8 Deluxe, "Olimar.nfc" (Super smash bros) works as well too.
